# Example sources.yaml configuration
# See docs/PLUGIN_GUIDE.md for full documentation

sources:
  # Weather for home location
  - id: weather_home
    type: weather
    enabled: true
    schedule: "*/15 * * * *"  # Every 15 minutes
    timeout: 30
    config:
      city: Seattle
      api_key: ${WEATHER_API_KEY}
    rendering:
      layout: modern_weather
      background: local
      background_query: weather/cloudy
    retry:
      enabled: true
      max_attempts: 3
      backoff_seconds: [1, 2, 4]
    fallback:
      use_cached: true
      max_age_hours: 24

  # Tesla vehicle
  - id: tesla_model_y
    type: tesla
    enabled: true
    schedule: "*/30 * * * *"  # Every 30 minutes
    timeout: 45
    config:
      vehicle_index: 0  # First vehicle
    rendering:
      layout: tesla_card
      background: local
      background_query: tesla/model_y

  # Ferry schedule
  - id: ferry_seattle_bainbridge
    type: ferry
    enabled: true
    schedule: "*/10 6-22 * * *"  # Every 10min, 6am-10pm
    timeout: 20
    config: {}  # Uses Config for now (FERRY_ROUTE, FERRY_HOME_TERMINAL)
    rendering:
      layout: ferry_map
      background: local
      background_query: ferry/puget_sound

  # Ambient Weather station
  - id: ambient_weather_home
    type: ambient_weather
    enabled: true
    schedule: "*/15 * * * *"  # Every 15 minutes
    timeout: 30
    config: {}  # Uses AMBIENT_API_KEY and AMBIENT_APP_KEY from .env
    rendering:
      layout: default
      background: local
      background_query: weather/sunny

  # Ambient Weather sensors (all temp/humidity sensors)
  - id: ambient_sensors_home
    type: ambient_sensors
    enabled: true
    schedule: "*/15 * * * *"  # Every 15 minutes
    timeout: 30
    config: {}  # Uses AMBIENT_API_KEY, AMBIENT_APP_KEY, and AMBIENT_SENSOR_NAMES from .env
    rendering:
      layout: default
      background: gradient

  # Internet speed test
  - id: speedtest_home
    type: speedtest
    enabled: true
    schedule: "0 */4 * * *"  # Every 4 hours
    timeout: 60
    config: {}  # Uses SPEEDTEST_URL and SPEEDTEST_TOKEN from .env
    rendering:
      layout: default
      background: local
      background_query: speedtest/network

  # Stock quote
  - id: stock_portfolio
    type: stock
    enabled: true
    schedule: "0 9-16 * * 1-5"  # Every hour, 9am-4pm, weekdays only
    timeout: 30
    config: {}  # Uses STOCK_API_KEY and STOCK_SYMBOL from .env
    rendering:
      layout: default
      background: local
      background_query: stock/charts

  # System health monitoring
  - id: system_health_local
    type: system_health
    enabled: true
    schedule: "*/5 * * * *"  # Every 5 minutes
    timeout: 20
    config: {}  # No config needed - monitors local system
    rendering:
      layout: default
      background: gradient

  # Ferry map (full-screen vessel tracking)
  - id: ferry_map_puget_sound
    type: ferry_map
    enabled: false  # Disabled by default (alternative to ferry schedule)
    schedule: "*/10 6-22 * * *"  # Every 10min, 6am-10pm
    timeout: 20
    config: {}  # Uses Config for FERRY_ROUTE
    rendering:
      layout: full_map
      background: ferry_map
